log_dir = '/home/citybuster/Data/SignalProcessing/Workdir'
legend = {
    'FMLDNN-bv5': 0,
    'FMLDNN-bv6': 1,
}

plot = dict(
    type='MLDNNPlot',
    log_dir=log_dir,
    config='fmldnn',
    legend=legend,
    # Set the configs about confusion maps
    confusion_map=[
        dict(
            type='ConfusionMap',
            log_dir=log_dir,
            name='confusion_map_fmldnn_201801A.pdf',
            method=dict(
                config='fmldnn_fmlnetv38-ia-channel-spatial-attention_famcauxhead-focal-0.1-1000_batchsize-640_lr-0.0010_dp-0.5_single-gpu_deepsig_201610A',
                has_snr_classifier=True,
                name='FMLDNN-V38',
            ),
        ),
        dict(
            type='ConfusionMap',
            log_dir=log_dir,
            name='confusion_map_fmldnn_201801A.pdf',
            method=dict(
                config='fmldnn_fmlnetv38-ia-channel-spatial-attention_famcauxhead-focal-0.1-1000_batchsize-640_lr-0.0015_dp-0.5_single-gpu_deepsig_201610A',
                has_snr_classifier=True,
                name='FMLDNN-V38',
            ),
        ),
        dict(
            type='ConfusionMap',
            log_dir=log_dir,
            name='confusion_map_fmldnn_201801A.pdf',
            method=dict(
                config='fmldnn_fmlnetv38-ia-channel-spatial-attention_famcauxhead-focal-0.1-1000_batchsize-640_lr-0.0020_dp-0.5_single-gpu_deepsig_201610A',
                has_snr_classifier=True,
                name='FMLDNN-V38',
            ),
        ),
        dict(
            type='ConfusionMap',
            log_dir=log_dir,
            name='confusion_map_fmldnn_201801A.pdf',
            method=dict(
                config='fmldnn_fmlnetv38-ia-channel-spatial-attention_famcauxhead-focal-0.1-1000_batchsize-640_lr-0.0025_dp-0.5_single-gpu_deepsig_201610A',
                has_snr_classifier=True,
                name='FMLDNN-V38',
            ),
        ),

        dict(
            type='ConfusionMap',
            log_dir=log_dir,
            name='confusion_map_fmldnn_201801A.pdf',
            method=dict(
                config='fmldnn_fmlnetv38-ia-channel-spatial-attention_famcauxhead-focal-1.0-1000_batchsize-640_lr-0.0010_dp-0.5_single-gpu_deepsig_201610A',
                has_snr_classifier=True,
                name='FMLDNN-V38',
            ),
        ),
        dict(
            type='ConfusionMap',
            log_dir=log_dir,
            name='confusion_map_fmldnn_201801A.pdf',
            method=dict(
                config='fmldnn_fmlnetv38-ia-channel-spatial-attention_famcauxhead-focal-1.0-1000_batchsize-640_lr-0.0015_dp-0.5_single-gpu_deepsig_201610A',
                has_snr_classifier=True,
                name='FMLDNN-V38',
            ),
        ),
        dict(
            type='ConfusionMap',
            log_dir=log_dir,
            name='confusion_map_fmldnn_201801A.pdf',
            method=dict(
                config='fmldnn_fmlnetv38-ia-channel-spatial-attention_famcauxhead-focal-1.0-1000_batchsize-640_lr-0.0020_dp-0.5_single-gpu_deepsig_201610A',
                has_snr_classifier=True,
                name='FMLDNN-V38',
            ),
        ),
        dict(
            type='ConfusionMap',
            log_dir=log_dir,
            name='confusion_map_fmldnn_201801A.pdf',
            method=dict(
                config='fmldnn_fmlnetv38-ia-channel-spatial-attention_famcauxhead-focal-1.0-1000_batchsize-640_lr-0.0025_dp-0.5_single-gpu_deepsig_201610A',
                has_snr_classifier=True,
                name='FMLDNN-V38',
            ),
        ),
    ],
)
