log_dir = '/home/citybuster/Data/SignalProcessing/Workdir'

legend = {
    'AlexNet-CO': 0,
    'GoogleNet-CO': 14,
    'VGGNet-CO': 26,
    'ResNet-CO': 24,

    'CNN2-IQ': 7,
    'CNN3-IQ': 8,
    'CNN3-AP': 9,
    'CNN4-IQ': 10,
    'DensCNN-IQ': 12,
    'ResCNN-IQ': 23,

    'CGDNN2-IQ': 1,
    'CGDNN2-AP': 2,
    'CLDNN-IQ': 3,
    'CLDNN-AP': 4,
    'CLDNN2-IQ': 5,
    'CLDNN2-AP': 6,
    'DSCLDNN': 13,

    'MLDNN': 15,
    'MLDNN-V3': 16,
    'MLDNN-V4': 17,
    'MLDNN-V5': 18,
    'MLDNN-V6': 19,
    'MLDNN-V7': 20,
    'MLDNN-V8': 21,
    'MLDNN-V9': 22,

    'DecisionTree-FB': 11,
    'SVM-FB': 25,

    'Fast MLDNN': 27,
    'Fast MLDNN-CE': 36,
    'Fast MLDNN-CE-CM': 37,
    'Fast MLDNN-FL-CM': 38,
    'Fast MLDNN-FL-CM-EP': 39,
    'Fast MLDNN-CE-CM-CN': 40,
    'Fast MLDNN-FL-CM-CN': 41,
    'Fast MLDNN-FL-CM-CN-EP': 42,
    'Fast MLDNN-CE-CM-CN-EP': 43
}


scatter = [
    'FM',
    'AM-SSB-SC',
    'AM-DSB-SC',
    'AM-SSB-WC',
    'AM-DSB-WC',
    'AM-DSB',
    'AM-SSB',
    'WBFM',
    '8PSK',
    'BPSK',
    'CPFSK',
    'GFSK',
    '4PAM',
    '16QAM',
    '64QAM',
    'QPSK',
    '32PSK',
    '16ASK',
    '32QAM',
    'GMSK',
    'OQPSK',
    '4ASK',
    '16PSK',
    '64APSK',
    '128QAM',
    '64QAM',
    '256QAM',
    'OOK',
]