log_dir = '/home/citybuster/Data/SignalProcessing/Workdir'

legend = {
    'AlexNet-CO': 0,
    'CGDNN2-IQ': 1,
    'CGDNN2-AP': 2,
    'CLDNN-IQ': 3,
    'CLDNN-AP': 4,
    'CLDNN2-IQ': 5,
    'CLDNN2-AP': 6,
    'CNN2-IQ': 7,
    'CNN3-IQ': 8,
    'CNN3-AP': 9,
    'CNN4-IQ': 10,
    'DecisionTree-FB': 11,
    'DensCNN-IQ': 12,
    'DSCLDNN': 13,
    'GoogleNet-CO': 14,
    'MLDNN': 15,
    'MLDNN-V3': 16,
    'MLDNN-V4': 17,
    'MLDNN-V5': 18,
    'MLDNN-V6': 19,
    'MLDNN-V7': 20,
    'MLDNN-V8': 21,
    'MLDNN-V9': 22,
    'ResCNN-IQ': 23,
    'ResNet-CO': 24,
    'SVM-FB': 25,
    'VGGNet-CO': 26,
}