import argparse
import json
from collections import Counter
from pathlib import Path


DEFAULT_DATA_ROOT = Path('/home/citybuster/Data/WirelessRadio/data/ModulationClassification')
DEFAULT_OUT = Path('docs/rcps/data_manifest.md')


def load_json(path):
    with path.open('r', encoding='utf-8') as f:
        return json.load(f)


def summarize_dataset(dataset_dir):
    rows = []
    metainfo = {}
    for split in ('train', 'validation', 'test'):
        ann_path = dataset_dir / f'{split}.json'
        if not ann_path.exists():
            rows.append((split, 0, '', 'missing'))
            continue
        ann = load_json(ann_path)
        data_list = ann.get('data_list', [])
        metainfo = ann.get('metainfo', metainfo)
        snrs = Counter(item.get('snr') for item in data_list if 'snr' in item)
        snr_text = ''
        if snrs:
            values = sorted(snrs)
            snr_text = f'{values[0]}..{values[-1]} ({len(values)} bins)'
        rows.append((split, len(data_list), snr_text, 'ok'))
    classes = metainfo.get('modulations', metainfo.get('classes', []))
    return classes, rows


def main():
    parser = argparse.ArgumentParser(description='Write the RCPS AMC data manifest.')
    parser.add_argument('--data-root', type=Path, default=DEFAULT_DATA_ROOT)
    parser.add_argument('--out', type=Path, default=DEFAULT_OUT)
    args = parser.parse_args()

    datasets = [
        args.data_root / 'DeepSig' / 'RadioML.2016.04C',
        args.data_root / 'DeepSig' / 'RadioML.2016.10A',
        args.data_root / 'DeepSig' / 'RadioML.2016.10B',
        args.data_root / 'DeepSig' / 'RadioML.2018.01A',
        args.data_root / 'Hisar' / 'HisarMod2019.1',
        args.data_root / 'UCSD' / 'RML22',
    ]

    lines = [
        '# RCPS Data Manifest',
        '',
        'This file is generated by `tools/rcps/prepare_amc_manifest.py`.',
        '',
        '## AMC Datasets',
        '',
        '| Dataset | Classes | Split | Samples | Reliability | Status |',
        '|---|---:|---|---:|---|---|',
    ]
    manifest = {}
    for dataset_dir in datasets:
        name = dataset_dir.relative_to(args.data_root).as_posix()
        if not dataset_dir.exists():
            lines.append(f'| `{name}` | 0 | all | 0 |  | missing |')
            manifest[name] = {'status': 'missing'}
            continue
        classes, rows = summarize_dataset(dataset_dir)
        manifest[name] = {
            'path': str(dataset_dir),
            'num_classes': len(classes),
            'classes': classes,
            'splits': {},
        }
        for split, count, reliability, status in rows:
            lines.append(
                f'| `{name}` | {len(classes)} | {split} | {count} | {reliability} | {status} |')
            manifest[name]['splits'][split] = {
                'samples': count,
                'reliability': reliability,
                'status': status,
            }

    lines.extend([
        '',
        '## Public Sources',
        '',
        '- DeepSig datasets: https://www.deepsig.ai/datasets/',
        '- HisarMod2019.1 paper: https://arxiv.org/abs/1911.04970',
        '- CIFAR-10: https://www.tensorflow.org/datasets/catalog/cifar10',
        '- CIFAR-10-C: https://zenodo.org/records/2535967',
        '- Speech Commands v0.02: https://tensorflow.google.cn/datasets/catalog/speech_commands',
        '',
    ])

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text('\n'.join(lines), encoding='utf-8')
    json_out = args.out.with_suffix('.json')
    json_out.write_text(json.dumps(manifest, indent=2, ensure_ascii=False), encoding='utf-8')
    print(f'Wrote {args.out} and {json_out}')


if __name__ == '__main__':
    main()
